#!/usr/bin/env bash

cd "$(dirname ${0})"

while read -u 9 certName 
do
    valid=$( \
        certbot certificates 2>/dev/null \
        | grep -A 4 -F "Name: ${certName}" \
        | awk '/Date/{print $6}' )

    echo -e "\n\n- - - - - -\nCert Name : ${certName} ; Valid : ${valid} Days\n"

    domains=$( \
        certbot certificates 2>/dev/null \
        | grep -A 4 -F "Name: ${certName}" \
        | sed -E -e '/Domains/!d' -e 's/^.*: //' -e 's/ /,/g' )

    certbot certonly \
            --manual \
            --non-interactive \
            --preferred-challenges dns \
            --server https://acme-v02.api.letsencrypt.org/directory \
            --manual-auth-hook    ./functions/authenticator.sh \
            --manual-cleanup-hook ./functions/cleanup.sh \
            --cert-name ${certName} \
            --domains ${domains}

done 9< <(  certbot certificates 2>/dev/null \
            | grep -F 'Certificate Name' \
            | awk '{print $3}' )
